### PR TITLE
adding simple cacheing functionality

### PR DESCRIPTION
**Pull request by choldgraf**
This adds a simple cache functionality, it is pretty bare-bones but may be useful? @consideRatio what do you think?

### CODE REVIEW

**Comment by consideRatio** [comment]
Nice functionality! The semantical hint I perceived from cache is that it would be a functionality that made future updates would be faster which didn't align with this functionality, and I would probably been clued in if it was instead called save or similar.

I've considered if `requests_cache` could help out for us to achieve the caching functionality I was thinking of, but I don't think so. By simply importing it in Python, you impact the behavior of the `requests` library, and if you make the same GET web request 100 times, it will only make it once and reuse the first response 99 times automatically. But, it wouldn't make sense for our web requests to GraphQL.

For saving/loading a dataframe from/to memory is the single objective, then using `pickle` may have been an option, but then you would not be able to load from .csv as you can with this PR.

```
import pickle
activity.to_pickle("/activity.pickle")
activity_from_pickle_file = pd.read_pickle("/tmp/activity.pickle")
```

Thanks for working on this project @choldgraf, I greatly appreciate it for creating changelogs! :heart:

**Comment by choldgraf** [comment]
Thanks for the feedback - what do you think about this as a first-step implementation that we can improve upon later?

I've had varying success with Pickle - it seems that when it breaks, it breaks in very unpredictable ways :-/ . Another option would be to use something a bit more heavy-weight like sqlalchemy to have a little database rather than CSV files...

**Comment by consideRatio** [comment]
Absolutely, go for a merge! If you introduce a breaking change later it won't be a big deal as you can just download the data again.

**Comment by choldgraf** [comment]
cool 👍

**Pull request merged**
